using Happy_Marriage.BusinessLogic.Interfaces;
using Happy_Marriage.Models;
using Happy_Marriage.Utilities;
using Org.BouncyCastle.Security;

namespace Happy_Marriage.BusinessLogic
{
    // Manages both User and User_Info TABLES
    public class UserManager:IUserManager
    {
        private DBEntityContext dBEntityContext;
        public UserManager() {
            dBEntityContext = new DBEntityContext();
        }

        public List<User> GetAll() { 
            var list = from users in dBEntityContext.Users select users;
            return list.ToList<User>();   
        }

        public User Add(User user) {
            dBEntityContext.Users.Add(user);
            return user;
        }

        public User Delete(User user){
            dBEntityContext.Users.Remove(user);
            return user;
        }

        public User Update(User user) { 
            dBEntityContext.Users.Update(user);
            return user;
        }

        public User GetUserByEmail(string email) {
            User user = dBEntityContext.Users.FirstOrDefault(u => u.Email == email);
            
            return user;
        }

        public User_Register Register(User_Register user_r) {
            User user = new User { 
                                   UserName = user_r.UserName,
                                   Email = user_r.Email,
                                   Password = user_r.Password,
                                   ContactNumber = user_r.ContactNumber,
                                   Role = "user",
                                   JoinedOn = new DateOnly()
                                 };
            //Insert data in Users table
            dBEntityContext.Users.Add(user);
            //After setting the data to the table, retrieve back to get id generated by MySql for the table and then set it to the second table
            user = GetUserByEmail(user_r.Email);
            User_Info user_Info = new User_Info { UserId = user.UserId,
                                                  FirstName=user_r.FirstName,
                                                  LastName=user_r.LastName,
                                                  Gender= user_r.Gender,
                                                  DateOfBirth=user_r.DateOfBirth,
                                                  Religion=user_r.Religion
                                                };
            //Insert data in Users_Info Table
            dBEntityContext.Users_Info.Add(user_Info);

            return user_r;
        }
    }
}
